[version]
path = "src/my_lib/__init__.py"

[build.targets.sdist]
exclude = [
  "/.github",
  "/docs",
  "/tests",
]

[build.targets.wheel]
packages = ["src/my_lib"]

[envs.test]
dependencies = [
  "coverage[toml]",
  "pytest",
  "pytest-cov",
]
extra-args = ["-vv"]
randomize = true
parallel = true

[envs.test.scripts]
unit = "pytest tests/unittests"
integration = "pytest tests/integration"
all = "pytest tests"
cov-test = "coverage run -m pytest tests"
cov-report = [
  #"coverage combine",
  "coverage report",
]
cov = [
  "cov-test",
  "cov-report",
]
